services:
  - type: web
    name: fondant-shop
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir src app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: BASE_URL
        sync: false
      - key: SESSION_COOKIE_SECURE
        value: True
      - key: PYTHON_VERSION
        value: 3.11.0
